name: Bazel
on: [push, pull_request]
jobs:
  bazel_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: "4.0.0"
      - name: Build all test targets
        run: bazel build //test:all
      - name: Build Release tar
        run: bazel build release
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/bin/release.tar.gz
          body: "Automatic release for ${{ github.sha }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: 1.0.1
